version: '3'
services:
    frontend:
        container_name: 'cwie-fba-frontend'
        build:
            context: .
        restart: always
        ports:
            - '8088:8080'
        command: npm run serve
        volumes:
            - '.:/app'
        networks:
            - cwie_fba
        # depends_on:
        #     - db
networks:
    cwie_fba: 
        driver: bridge
# volumes:
#     db_data:
#         driver: local

